# Permalinks
permalink:        pretty
# relative_permalinks: true
paginate: 10

excerpt_separator: <!--more-->

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Random Code
email: satriyo.796@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Some codes, some rants, and something else
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://arseto.github.io" # the base hostname & protocol for your site
twitter_username: satriyo796
github_username:  satriyo796

# Build settings
# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:
  - jekyll-gist
  - jekyll-paginate
